### ISSUE TITLE
npm start and then boom!

### ISSUE THREAD

**Issue by extra-it** [dbertella/react-hot-reload-starter#1]
Hi Daniele,

I have installed your package but when I run npm start I have the following exception:

C:\dev\temp\react-hot-reload-starter-master>npm start

> react-hot-loader-starter@1.0.0 start C:\dev\temp\react-hot-reload-starter-master
> node server.js

Hash: 21135a99dcf477b9080d
Version: webpack 1.12.3
Time: 7880ms
    Asset    Size  Chunks             Chunk Names
bundle.js  271 kB       0  [emitted]  main
chunk    {0} bundle.js (main) 216 kB [rendered]
    [0] multi main 52 bytes {0} [built] [1 error]
    [1](webpack)-dev-server/client?http://localhost:3000 2.14 kB {0} [built]
    [2](webpack)/~/node-libs-browser/~/url/url.js 22.3 kB {0} [built]
    [3](webpack)/~/node-libs-browser/~/punycode/punycode.js 14.6 kB {0} [built]
    [4](webpack)/buildin/module.js 251 bytes {0} [built]
    [5](webpack)/~/node-libs-browser/~/url/~/querystring/index.js 127 bytes {0} [built]
    [6](webpack)/~/node-libs-browser/~/url/~/querystring/decode.js 2.4 kB {0} [built]
    [7](webpack)/~/node-libs-browser/~/url/~/querystring/encode.js 2.09 kB {0} [built]
    [8](webpack)-dev-server/~/socket.io-client/index.js 37 bytes {0} [built]
    [9](webpack)-dev-server/~/socket.io-client/lib/index.js 1.5 kB {0} [built]
   [10](webpack)-dev-server/~/socket.io-client/lib/url.js 1.53 kB {0} [built]
   [11](webpack)-dev-server/~/socket.io-client/~/parseuri/index.js 690 bytes {0} [built]
   [12](webpack)-dev-server/~/socket.io-client/~/debug/debug.js 2.46 kB {0} [built]
   [13](webpack)-dev-server/~/socket.io-client/~/socket.io-parser/index.js 7.63 kB {0} [built]
   [14](webpack)-dev-server/~/socket.io-client/~/socket.io-parser/~/json3/lib/json3.js 40.1 kB {0} [built]
   [15](webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [16](webpack)-dev-server/~/socket.io-client/~/socket.io-parser/~/isarray/index.js 120 bytes {0} [built]
   [17](webpack)-dev-server/~/socket.io-client/~/component-emitter/index.js 3 kB {0} [built]
   [18](webpack)-dev-server/~/socket.io-client/~/socket.io-parser/binary.js 3.84 kB {0} [built]
   [19](webpack)-dev-server/~/socket.io-client/~/socket.io-parser/is-buffer.js 252 bytes {0} [built]
   [20](webpack)-dev-server/~/socket.io-client/lib/manager.js 11 kB {0} [built]
   [21](webpack)-dev-server/~/socket.io-client/~/engine.io-client/index.js 38 bytes {0} [built]
   [22](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/index.js 140 bytes {0} [built]
   [23](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/socket.js 16.9 kB {0} [built]
   [24](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/index.js 1.08 kB {0} [built]
   [25](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/xmlhttprequest.js 1.16 kB {0} [built]
   [26](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/has-cors/index.js 458 bytes {0} [built]
   [27](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/has-cors/~/global/index.js 257 bytes {0} [built]
   [28](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/polling-xhr.js 7.92 kB {0} [built]
   [29](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/polling.js 4.85 kB {0} [built]
   [30](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/transport.js 2.74 kB {0} [built]
   [31](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/lib/browser.js 14.4 kB {0} [built]
   [32](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/lib/keys.js 297 bytes {0} [built]
   [33](webpack)-dev-server/~/socket.io-client/~/has-binary/index.js 1.08 kB {0} [built]
   [34](webpack)-dev-server/~/socket.io-client/~/has-binary/~/isarray/index.js 120 bytes {0} [built]
   [35](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/arraybuffer.slice/index.js 725 bytes {0} [built]
   [36](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/base64-arraybuffer/lib/base64-arraybuffer.js 1.7 kB {0} [built]
   [37](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/after/index.js 685 bytes {0} [built]
   [38](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/utf8/utf8.js 6.38 kB {0} [built]
   [39](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/blob/index.js 2.2 kB {0} [built]
   [40](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/parseqs/index.js 708 bytes {0} [built]
   [41](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/component-inherit/index.js 146 bytes {0} [built]
   [42](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/debug/browser.js 3.28 kB {0} [built]
   [43](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/debug/debug.js 4.1 kB {0} [built]
   [44](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/debug/~/ms/index.js 2.02 kB {0} [built]
   [45](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/polling-jsonp.js 4.82 kB {0} [built]
   [46](webpack)-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/websocket.js 4.57 kB {0} [built]
   [47](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/browser.js 831 bytes {0} [built]
   [48](webpack)-dev-server/~/socket.io-client/~/indexof/index.js 199 bytes {0} [built]
   [49](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/parseuri/index.js 1.19 kB {0} [built]
   [50](webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/parsejson/index.js 842 bytes {0} [built]
   [51](webpack)-dev-server/~/socket.io-client/lib/socket.js 6.99 kB {0} [built]
   [52](webpack)-dev-server/~/socket.io-client/~/to-array/index.js 216 bytes {0} [built]
   [53](webpack)-dev-server/~/socket.io-client/lib/on.js 370 bytes {0} [built]
   [54](webpack)-dev-server/~/socket.io-client/~/component-bind/index.js 474 bytes {0} [built]
   [55](webpack)-dev-server/~/socket.io-client/~/object-component/index.js 1.18 kB {0} [built]
   [56](webpack)-dev-server/~/socket.io-client/~/backo2/index.js 1.4 kB {0} [built]
   [57](webpack)-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
   [58](webpack)-dev-server/~/strip-ansi/~/ansi-regex/index.js 135 bytes {0} [built]
   [59](webpack)/hot/only-dev-server.js 2.25 kB {0} [built]
   [60](webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./src/index.js
Module build failed: SyntaxError: C:/dev/temp/react-hot-reload-starter-master/src/index.js: Unexpected token (12:1)
  10 |
  11 | ReactDOM.render(

> 12 |  <Router>
>      |  ^
>   13 |          <Route path="/" component={App}>
>   14 |                  <IndexRoute component={Home} />
>   15 |                  <Route path="/about" component={About} />
>     at Parser.pp.raise (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\location.js:24:13)
>     at Parser.pp.unexpected (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\util.js:91:8)
>     at Parser.pp.parseExprAtom (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:514:12)
>     at Parser.pp.parseExprSubscripts (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:267:19)
>     at Parser.pp.parseMaybeUnary (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:247:19)
>     at Parser.pp.parseExprOps (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:178:19)
>     at Parser.pp.parseMaybeConditional (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:160:19)
>     at Parser.pp.parseMaybeAssign (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:123:19)
>     at Parser.pp.parseExprListItem (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:978:16)
>     at Parser.pp.parseCallExpressionArguments (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:343:20)
>  @ multi main
> webpack: bundle is now VALID.

**Comment by dbertella** [comment]
Hi alessio, thank you for trying the package. I will look into it but
unfortunately I don't have a windows environment to test it out. Can you
dig into it and check what is causing the error? Check which version of
react-router you installed, because I had some problem with it. Check if is
react router the issue loading another component instead of Router.

Try with something like that for example:
ReactDOM.render(<About />, document.getElementById('root'));

2015-11-06 16:25 GMT+01:00 AlessioVecchi notifications@github.com:

> Hi Daniele,
> 
> I have installed your package but when I run npm start I have the
> following exception:
> 
> C:\dev\temp\react-hot-reload-starter-master>npm start
> 
> react-hot-loader-starter@1.0.0 start
> C:\dev\temp\react-hot-reload-starter-master
> node server.js
> 
> Hash: 21135a99dcf477b9080d
> Version: webpack 1.12.3
> Time: 7880ms
> Asset Size Chunks Chunk Names
> bundle.js 271 kB 0 [emitted] main
> chunk {0} bundle.js (main) 216 kB [rendered]
> [0] multi main 52 bytes {0} [built] [1 error]
> 1 http://webpack-dev-server/client?http://localhost:3000 2.14 kB {0}
> [built]
> 2 http://webpack/~/node-libs-browser/~/url/url.js 22.3 kB {0} [built]
> 3 http://webpack/~/node-libs-browser/~/punycode/punycode.js 14.6 kB {0}
> [built]
> 4 http://webpack/buildin/module.js 251 bytes {0} [built]
> 5 http://webpack/~/node-libs-browser/~/url/~/querystring/index.js 127
> bytes {0} [built]
> 6 http://webpack/~/node-libs-browser/~/url/~/querystring/decode.js 2.4
> kB {0} [built]
> 7 http://webpack/~/node-libs-browser/~/url/~/querystring/encode.js 2.09
> kB {0} [built]
> 8 http://webpack-dev-server/~/socket.io-client/index.js 37 bytes {0}
> [built]
> 9 http://webpack-dev-server/~/socket.io-client/lib/index.js 1.5 kB {0}
> [built]
> 10 http://webpack-dev-server/~/socket.io-client/lib/url.js 1.53 kB {0}
> [built]
> 11 http://webpack-dev-server/~/socket.io-client/~/parseuri/index.js 690
> bytes {0} [built]
> 12 http://webpack-dev-server/~/socket.io-client/~/debug/debug.js 2.46
> kB {0} [built]
> 13 http://webpack-dev-server/~/socket.io-client/~/socket.io-parser/index.js
> 7.63 kB {0} [built]
> 14 http://webpack-dev-server/~/socket.io-client/~/socket.io-parser/~/json3/lib/json3.js
> 40.1 kB {0} [built]
> 15 http://webpack/buildin/amd-options.js 43 bytes {0} [built]
> 16 http://webpack-dev-server/~/socket.io-client/~/socket.io-parser/~/isarray/index.js
> 120 bytes {0} [built]
> 17 http://webpack-dev-server/~/socket.io-client/~/component-emitter/index.js
> 3 kB {0} [built]
> 18 http://webpack-dev-server/~/socket.io-client/~/socket.io-parser/binary.js
> 3.84 kB {0} [built]
> 19 http://webpack-dev-server/~/socket.io-client/~/socket.io-parser/is-buffer.js
> 252 bytes {0} [built]
> 20 http://webpack-dev-server/~/socket.io-client/lib/manager.js 11 kB
> {0} [built]
> 21 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/index.js
> 38 bytes {0} [built]
> 22 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/index.js
> 140 bytes {0} [built]
> 23 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/socket.js
> 16.9 kB {0} [built]
> 24 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/index.js
> 1.08 kB {0} [built]
> 25 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/xmlhttprequest.js
> 1.16 kB {0} [built]
> 26 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/has-cors/index.js
> 458 bytes {0} [built]
> 27 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/has-cors/~/global/index.js
> 257 bytes {0} [built]
> 28 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/polling-xhr.js
> 7.92 kB {0} [built]
> 29 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/polling.js
> 4.85 kB {0} [built]
> 30 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/transport.js
> 2.74 kB {0} [built]
> 31 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/lib/browser.js
> 14.4 kB {0} [built]
> 32 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/lib/keys.js
> 297 bytes {0} [built]
> 33 http://webpack-dev-server/~/socket.io-client/~/has-binary/index.js
> 1.08 kB {0} [built]
> 34 http://webpack-dev-server/~/socket.io-client/~/has-binary/~/isarray/index.js
> 120 bytes {0} [built]
> 35 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/arraybuffer.slice/index.js
> 725 bytes {0} [built]
> 36 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/base64-arraybuffer/lib/base64-arraybuffer.js
> 1.7 kB {0} [built]
> 37 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/after/index.js
> 685 bytes {0} [built]
> 38 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/utf8/utf8.js
> 6.38 kB {0} [built]
> 39 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/engine.io-parser/~/blob/index.js
> 2.2 kB {0} [built]
> 40 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/parseqs/index.js
> 708 bytes {0} [built]
> 41 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/component-inherit/index.js
> 146 bytes {0} [built]
> 42 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/debug/browser.js
> 3.28 kB {0} [built]
> 43 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/debug/debug.js
> 4.1 kB {0} [built]
> 44 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/debug/~/ms/index.js
> 2.02 kB {0} [built]
> 45 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/polling-jsonp.js
> 4.82 kB {0} [built]
> 46 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/lib/transports/websocket.js
> 4.57 kB {0} [built]
> 47 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/browser.js
> 831 bytes {0} [built]
> 48 http://webpack-dev-server/~/socket.io-client/~/indexof/index.js 199
> bytes {0} [built]
> 49 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/parseuri/index.js
> 1.19 kB {0} [built]
> 50 http://webpack-dev-server/~/socket.io-client/~/engine.io-client/~/parsejson/index.js
> 842 bytes {0} [built]
> 51 http://webpack-dev-server/~/socket.io-client/lib/socket.js 6.99 kB
> {0} [built]
> 52 http://webpack-dev-server/~/socket.io-client/~/to-array/index.js 216
> bytes {0} [built]
> 53 http://webpack-dev-server/~/socket.io-client/lib/on.js 370 bytes {0}
> [built]
> 54 http://webpack-dev-server/~/socket.io-client/~/component-bind/index.js
> 474 bytes {0} [built]
> 55 http://webpack-dev-server/~/socket.io-client/~/object-component/index.js
> 1.18 kB {0} [built]
> 56 http://webpack-dev-server/~/socket.io-client/~/backo2/index.js 1.4
> kB {0} [built]
> 57 http://webpack-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
> 58 http://webpack-dev-server/~/strip-ansi/~/ansi-regex/index.js 135
> bytes {0} [built]
> 59 http://webpack/hot/only-dev-server.js 2.25 kB {0} [built]
> 60 http://webpack/hot/log-apply-result.js 813 bytes {0} [built]
> 
> ERROR in ./src/index.js
> Module build failed: SyntaxError:
> C:/dev/temp/react-hot-reload-starter-master/src/index.js: Unexpected token
> (12:1)
> 10 |
> 11 | ReactDOM.render(
> 
> 12 |
> | ^
> 13 |
> 14 |
> 15 |
> at Parser.pp.raise
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\location.js:24:13)
> at Parser.pp.unexpected
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\util.js:91:8)
> at Parser.pp.parseExprAtom
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:514:12)
> at Parser.pp.parseExprSubscripts
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:267:19)
> at Parser.pp.parseMaybeUnary
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:247:19)
> at Parser.pp.parseExprOps
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:178:19)
> at Parser.pp.parseMaybeConditional
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:160:19)
> at Parser.pp.parseMaybeAssign
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:123:19)
> at Parser.pp.parseExprListItem
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:978:16)
> at Parser.pp.parseCallExpressionArguments
> (C:\dev\temp\react-hot-reload-starter-master\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:343:20)
> @ multi main
> webpack: bundle is now VALID.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dbertella/react-hot-reload-starter/issues/1.

## 

Daniele Bertella
*Front end developer *

+39.340.490.57.80
info@danielebertella.com
LinkedIn: danielebertella http://it.linkedin.com/in/danielebertella/
Twitter: _denb https://twitter.com/_denb
www.danielebertella.com
